server: xx.yy:443 #修改为服务端分配的域名及端口

obfs: #若服务端没有配置混淆密码，此部分必须删除。
  type: salamander
  salamander:
    password: 3452e3b8k2 #修改为服务端配置的混淆密码

auth: 123a65h7890 #修改为服务端配置的验证密码

bandwidth:
  up: 20 mbps
  down: 100 mbps

socks5:
  listen: 127.0.0.1:1080

http:
  listen: 127.0.0.1:8080
